---
version: "2"
services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft
    network_mode: host
    environment:
      - PUID=998
      - PGID=100
      - EULA=TRUE
      - VERSION=1.17.1
      - MEMORY=2G
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - MAX_PLAYERS=15
      - ALLOW_NETHER=true
      - ENABLE_COMMAND_BLOCK=true
      - ONLINE_MODE=FALSE
      - OPS=Zoe8338
      - ICON=https://www.pikpng.com/pngl/m/11-111774_block-of-grass-from-the-game-minecraft-minecraft.png
      - SEED=-4379469131957062683
      - VIEW_DISTANCE=7
      - SERVER_NAME=SMP - Just For Fun
      - ALLOW_FLIGHT=TRUE
    ports:
      - 25565:25565
    volumes:
      - /srv/dev-disk-by-uuid-0242c912-32c0-435e-9cd4-3d99a9a7f576/Minecraft:/data
    restart: always
    # https://github.com/itzg/docker-minecraft-server#opadministrator-players
