---
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBFOLDER=/ #optional
      - KEYBOARD=pt-br-qwerty #optional
      -e AUTO_LOGIN=false
    volumes:
      - /home/zoe/webtop-ubuntu-kde-001/data:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3080:3000
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
